kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: backend
    image: laradock/workspace:latest-7.4
    commands:
      - php -v
      - composer -V
      - cp .env.example .env
      - composer install --prefer-dist
      - php artisan key:generate
      - php artisan test
