php:
  repository: "paulknisely/test-laravel-cicd-app"
  tag: "latest"
  fpmEnable: true
  envVars:
    - name: APP_ENV
      value: production
    - name: APP_DEBUG
      value: false
    - name: DB_PORT
      value: 3306
    - name: DB_HOST
      value: localhost
